<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_5834c14c62151',
  'title' => 'About Us Details',
  'fields' => array (
    array (
      'key' => 'field_58265bb10cb13',
      'label' => 'About Us Title',
      'name' => 'about_us_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'formatting' => 'html',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_58265c2c0cb14',
      'label' => 'About Us Details',
      'name' => 'about_us_details',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => 'br',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page_about-us.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
  ),
  'active' => 1,
  'description' => '',
  'old_ID' => 51,
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_5834c14c87518',
  'title' => 'Contact Details',
  'fields' => array (
    array (
      'key' => 'field_580c88cd84e6c',
      'label' => 'Contact Details Title',
      'name' => 'contact_details_title',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => 'br',
    ),
    array (
      'key' => 'field_580c895e84e6d',
      'label' => 'Contact Details Content',
      'name' => 'contact_details_content',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => 'br',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page_contact-us.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
  ),
  'active' => 1,
  'description' => '',
  'old_ID' => 9,
  'local' => 'php',
));

acf_add_local_field_group(array (
  'key' => 'group_583758b458c27',
  'title' => 'Footer Content',
  'fields' => array (
    array (
      'key' => 'field_5837598904251',
      'label' => 'Footer Body',
      'name' => 'footer_body',
      'type' => 'wysiwyg',
      'instructions' => 'Enter footer text content here.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 0,
    ),
    array (
      'key' => 'field_58388d5e88c9c',
      'label' => 'Social Links',
      'name' => 'social_links',
      'type' => 'repeater',
      'instructions' => 'Add a social link by selecting a social media platform and entering the URL',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => '',
      'layout' => 'table',
      'button_label' => 'Add Row',
      'sub_fields' => array (
        array (
          'key' => 'field_58388d7388c9d',
          'label' => 'social media platform',
          'name' => 'social_media_platform',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'FaceBook' => 'FaceBook',
            'Twitter' => 'Twitter',
            'Vimeo' => 'Vimeo',
            'Youtube' => 'Youtube',
          ),
          'allow_null' => 0,
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => '',
          'layout' => 'vertical',
          'return_format' => 'value',
        ),
        array (
          'key' => 'field_58388dc088c9e',
          'label' => 'Social Media URL',
          'name' => 'social_media_url',
          'type' => 'url',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-footer',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_5834c3c1cd447',
  'title' => 'Work Article',
  'fields' => array (
    array (
      'key' => 'field_5834c5ebcbaa9',
      'label' => 'Client',
      'name' => 'client',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
    ),
    array (
      'key' => 'field_5834c557e6d24',
      'label' => 'Work Content',
      'name' => 'work_content',
      'type' => 'flexible_content',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'button_label' => 'Add Content',
      'min' => '',
      'max' => '',
      'layouts' => array (
        array (
          'key' => '5834c55c15b79',
          'name' => 'body_content',
          'label' => 'Body Content',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_5834c56de6d25',
              'label' => 'Body Content',
              'name' => 'body_content',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5834c6f33db49',
          'name' => 'image',
          'label' => 'Image(s)',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_5834c7173db4a',
              'label' => 'Images',
              'name' => 'images',
              'type' => 'gallery',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'min' => '',
              'max' => '',
              'insert' => 'append',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '5834c896661c0',
          'name' => 'body_content_with_quote',
          'label' => 'Body Content With Pull Quote',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_583891bac0c70',
              'label' => 'Pull Quote',
              'name' => 'pull_quote',
              'type' => 'textarea',
              'instructions' => 'Please enter Pull Quote here.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => 6,
              'new_lines' => 'wpautop',
            ),
            array (
              'key' => 'field_583891dbc0c71',
              'label' => 'Body Content',
              'name' => 'body_content',
              'type' => 'wysiwyg',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'tabs' => 'all',
              'toolbar' => 'full',
              'media_upload' => 1,
            ),
          ),
          'min' => '',
          'max' => '',
        ),
        array (
          'key' => '58389225ee993',
          'name' => 'video',
          'label' => 'Video',
          'display' => 'row',
          'sub_fields' => array (
            array (
              'key' => 'field_5838926dee994',
              'label' => 'Video URL',
              'name' => 'video_url',
              'type' => 'oembed',
              'instructions' => 'Copy and paste the youtube or vimeo URL into the field.',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => 'video-container',
                'id' => '',
              ),
              'width' => '',
              'height' => '',
            ),
            array (
              'key' => 'field_583892d2ee995',
              'label' => 'Play Button Colour',
              'name' => 'play_button_colour',
              'type' => 'color_picker',
              'instructions' => '#2fbeb6 - green/cyan
#404040 - dark gray',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
            ),
            array (
              'key' => 'field_5838947aee996',
              'label' => 'Video Placeholder',
              'name' => 'video_placeholder',
              'type' => 'image',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'return_format' => 'array',
              'preview_size' => 'thumbnail',
              'library' => 'all',
              'min_width' => '',
              'min_height' => '',
              'min_size' => '',
              'max_width' => '',
              'max_height' => '',
              'max_size' => '',
              'mime_types' => '',
            ),
          ),
          'min' => '',
          'max' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'portfolio',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_5834c01b78688',
  'title' => 'Work Group',
  'fields' => array (
    array (
      'key' => 'field_5834c1c4be7df',
      'label' => 'Caption',
      'name' => 'caption',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'maxlength' => '',
      'rows' => '',
      'new_lines' => 'wpautop',
    ),
    array (
      'key' => 'field_5834b52db127a',
      'label' => 'Image Set',
      'name' => 'imageset',
      'type' => 'gallery',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'min' => 1,
      'max' => 3,
      'insert' => 'append',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'post',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'seamless',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;
?>